export {
  DOXA_AUTH_MIGRATION_URL,
  DOXA_AUTH_INFRASTRUCTURE_MIGRATION_URL,
  DOXA_AUTH_CHALLENGE_BINDING_MIGRATION_URL,
  DOXA_AUTH_IMPERSONATION_MIGRATION_URL,
  installAuthSchema,
} from './migration.js'
